# Generated by Django 2.0.3 on 2018-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='rating',
        ),
        migrations.AlterField(
            model_name='log',
            name='mood_field',
            field=models.CharField(max_length=400),
        ),
    ]
